name: Deploy Frontend to Server

on:
  push:
    branches:
      - main  # Trigger on changes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the code from the repo

    - name: Install sshpass
      run: |
        sudo apt-get install sshpass  # Install sshpass for password-based SSH

    - name: Add server to known hosts to bypass SSH verification
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: SSH into server, pull latest code, build, and deploy
      run: |
        sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          # Navigate to the trackerfrontend directory
          cd /trackerfrontend || exit
          # Pull the latest changes from the repo
          git pull origin main || exit
          # Install dependencies and build the project
          npm install || exit
          npm run build || exit
          # Copy dist folder to Nginx directory
          rsync -avz --delete ./dist/ /var/www/html/ || exit
        EOF

    - name: Restart Nginx
      run: |
        sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} 'sudo systemctl restart nginx'
