name: Deploy Frontend to Server

on:
  push:
    branches:
      - main  # Trigger on changes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the code from the repo

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Set the node version you’re using

    - name: Install dependencies
      run: |
        npm install

    - name: Build the frontend
      run: |
        npm run build

    - name: Set up SSH agent
      run: |
        eval $(ssh-agent -s)  # Start the SSH agent
        echo "$SSH_PRIVATE_KEY" | ssh-add -  # Add the private key

    - name: Copy dist folder to server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        rsync -avz --delete ./dist/ $SERVER_USER@$SERVER_IP:/var/www/html/

    - name: Restart Nginx
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP 'sudo systemctl restart nginx'
