name: Deploy Frontend to Server

on:
  push:
    branches:
      - main  # Trigger on changes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the code from the repo

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Set the node version you’re using

    - name: Install dependencies
      run: |
        npm install

    - name: Build the frontend
      run: |
        npm run build

    - name: Check if dist directory exists
      run: |
        ls -alh ./dist

    - name: Install sshpass
      run: |
        sudo apt-get install sshpass  # Install sshpass for password-based SSH

    - name: Add server to known hosts to bypass SSH verification
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Copy dist folder to server using password
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}  # Store your password in GitHub Secrets
      run: |
        # Use sshpass to provide the password for SSH authentication
        sshpass -p "$SSH_PASSWORD" rsync -avz --delete ./dist/ $SERVER_USER@$SERVER_IP:/var/www/html/

    - name: Restart Nginx
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        # Restart nginx using password authentication with sshpass
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP 'sudo systemctl r
